stages:
  - build
  - test
  - deploy-branch
  - deploy-staging
  - deploy-production

build:
  stage: build
  script:
    - npm install
    - npm run build
    - mvn clean install -DskipTests

run_tests:
  stage: test
  script:
    - cat $RUN_TESTS_SCRIPT >> run_tests.sh
    - ./run_tests.sh

run_deploy_staging:
  stage: deploy-staging
  only:
    - development
  except:
    - schedules
  script:
    - cat $RUN_DEPLOY_STAGING_SCRIPT >> run_deploy_staging.sh
    - ./run_deploy_staging.sh

run_deploy_production:
  stage: deploy-production
  only:
    - main
  except:
    - schedules
  script:
    - cat $RUN_DEPLOY_PRODUCTION_SCRIPT >> run_deploy_production.sh
    - ./run_deploy_production.sh

