stages:
  - build
  - test
  - deploy-branch
  - deploy-staging
  - deploy-production

build:
  image: $BUILD_IMAGE
  tags:
    - $BUILD_TAG
  stage: build
  script:
    - npm install
    - npm run build
    - mvn clean install -DskipTests

run_tests:
  image: $TESTS_IMAGE
  tags:
    - $TESTS_TAG
  stage: test
  script:
    - cat $RUN_TESTS_SCRIPT >> run_tests.sh
    - chmod +x run_tests.sh
    - source run_tests.sh

run_deploy_staging:
  image: $DEPLOY_STAGING_IMAGE
  tags:
    - $DEPLOY_STAGING_TAG
  stage: deploy-staging
  only:
    - development
  except:
    - schedules
  script:
    - cat $RUN_DEPLOY_STAGING_SCRIPT >> run_deploy_staging.sh
    - chmod +x run_deploy_staging.sh
    - source run_deploy_staging.sh

run_deploy_production:
  image: $DEPLOY_PRODUCTION_IMAGE
  tags:
    - $DEPLOY_PRODUCTION_TAG
  stage: deploy-production
  only:
    - main
  except:
    - schedules
  script:
    - cat $RUN_DEPLOY_PRODUCTION_SCRIPT >> run_deploy_production.sh
    - chmod +x run_deploy_production.sh
    - source run_deploy_production.sh

